package br.com.simweb2.model.entities;
// Generated 23/02/2013 11:46:33 by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Atendente generated by hbm2java
 */

@Entity
@Table(name="atendente")
@PrimaryKeyJoinColumn(name="PESSOA_idPESSOA")
public class Atendente extends Pessoa implements java.io.Serializable {

    private static final long serialVersionUID = 973649105911856161L;

    private String numeroderegistro;

    public Atendente() {
    }

    public String getNumeroderegistro() {
        return this.numeroderegistro;
    }
    
    public void setNumeroderegistro(String numeroderegistro) {
        this.numeroderegistro = numeroderegistro;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 31 * hash + (this.numeroderegistro != null ? this.numeroderegistro.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Atendente other = (Atendente) obj;
        if (this.numeroderegistro != other.numeroderegistro && (this.numeroderegistro == null || !this.numeroderegistro.equals(other.numeroderegistro))) {
            return false;
        }
        return true;
    }

}


