package br.com.simweb2.model.entities;
// Generated 23/02/2013 11:46:33


import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Enfermeiro generated by hbm2java
 */

@Entity
@Table(name="enfermeiro")
@PrimaryKeyJoinColumn(name="PESSOA_idPESSOA")
public class Enfermeiro extends Pessoa implements java.io.Serializable {
    
    private static final long serialVersionUID = 4684156915174996526L;
     
    private String registrodaunidade;
    private String cns;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date dataatribuicao;
    private String situacao;

    public Enfermeiro() {
    }

    public String getRegistrodaunidade() {
        return registrodaunidade;
    }

    public void setRegistrodaunidade(String registrodaunidade) {
        this.registrodaunidade = registrodaunidade;
    }

    public String getCns() {
        return cns;
    }

    public void setCns(String cns) {
        this.cns = cns;
    }

    public Date getDataatribuicao() {
        return dataatribuicao;
    }

    public void setDataatribuicao(Date dataatribuicao) {
        this.dataatribuicao = dataatribuicao;
    }

    public String getSituacao() {
        return situacao;
    }

    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 73 * hash + (this.registrodaunidade != null ? this.registrodaunidade.hashCode() : 0);
        hash = 73 * hash + (this.cns != null ? this.cns.hashCode() : 0);
        hash = 73 * hash + (this.dataatribuicao != null ? this.dataatribuicao.hashCode() : 0);
        hash = 73 * hash + (this.situacao != null ? this.situacao.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Enfermeiro other = (Enfermeiro) obj;
        if ((this.registrodaunidade == null) ? (other.registrodaunidade != null) : !this.registrodaunidade.equals(other.registrodaunidade)) {
            return false;
        }
        if ((this.cns == null) ? (other.cns != null) : !this.cns.equals(other.cns)) {
            return false;
        }
        if (this.dataatribuicao != other.dataatribuicao && (this.dataatribuicao == null || !this.dataatribuicao.equals(other.dataatribuicao))) {
            return false;
        }
        if (this.situacao != other.situacao && (this.situacao == null || !this.situacao.equals(other.situacao))) {
            return false;
        }
        return true;
    }    
    
}


