package br.com.simweb2.model.entities;
// Generated 23/02/2013

import java.util.List;
import javax.persistence.*;
import org.hibernate.annotations.ForeignKey;



/**
 * Estado generated by hbm2java
 */

@Entity
@Table(name="estado")

public class Estado implements java.io.Serializable {
    
    
    private static final long serialVersionUID = 8787014459071770166L;
    
    @Id
    @GeneratedValue
    @Column(name="idEstado")
    private Integer idEstado;   
    @Column(name="nome")
    private String nome;   
    @Column(name="uf")
    private String uf;
    
    @OneToMany(fetch= FetchType.LAZY)
    @ForeignKey(name="EstadoCidade")
    private List<Cidade> cidades;   

    public Estado() {
    }

    public Integer getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getUf() {
        return this.uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + (this.idEstado != null ? this.idEstado.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Estado other = (Estado) obj;
        if (this.idEstado != other.idEstado && (this.idEstado == null || !this.idEstado.equals(other.idEstado))) {
            return false;
        }
        return true;
    }

   

  
  
}