package br.com.simweb2.model.entities;
// Generated 23/02/2013 11:46:33 

import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;




/**
 * Paciente generated by hbm2java
 */

@Entity
@Table(name="paciente")
@PrimaryKeyJoinColumn(name="PESSOA_idPESSOA")
public class Paciente  extends Pessoa implements java.io.Serializable {
    
    
    private static final long serialVersionUID = 98414908679133750L;

    private Integer registrodaunidade;
    private String profissao;
    private String localdetrabalho;

    public Paciente() {
    }

    public Integer getRegistrodaunidade() {
        return registrodaunidade;
    }

    public void setRegistrodaunidade(Integer registrodaunidade) {
        this.registrodaunidade = registrodaunidade;
    }

    public String getProfissao() {
        return profissao;
    }

    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

    public String getLocaldetrabalho() {
        return localdetrabalho;
    }

    public void setLocaldetrabalho(String localdetrabalho) {
        this.localdetrabalho = localdetrabalho;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + (this.registrodaunidade != null ? this.registrodaunidade.hashCode() : 0);
        hash = 37 * hash + (this.profissao != null ? this.profissao.hashCode() : 0);
        hash = 37 * hash + (this.localdetrabalho != null ? this.localdetrabalho.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Paciente other = (Paciente) obj;
        if (this.registrodaunidade != other.registrodaunidade && (this.registrodaunidade == null || !this.registrodaunidade.equals(other.registrodaunidade))) {
            return false;
        }
        if ((this.profissao == null) ? (other.profissao != null) : !this.profissao.equals(other.profissao)) {
            return false;
        }
        if ((this.localdetrabalho == null) ? (other.localdetrabalho != null) : !this.localdetrabalho.equals(other.localdetrabalho)) {
            return false;
        }
        return true;
    }
    
        
  
}


