package br.com.simweb2.model.entities;
// Generated 23/02/2013

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Pessoa generated by hbm2java
 */

@Entity
@Table(name="pessoa")
@Inheritance(strategy= InheritanceType.JOINED)
public class Pessoa  implements java.io.Serializable {

    
     private static final long serialVersionUID = -8574310121722203642L;
     

     @Id
     @GeneratedValue
     @Column(name="idPESSOA", nullable=true)     
     private Integer idPessoa;
     
     @ManyToOne(fetch= FetchType.EAGER)
     @JoinColumn(name="CIDADE_idCIDADE")
     private Cidade cidade;
     
     
     
     private String nome;
        
     @Temporal(javax.persistence.TemporalType.DATE)
     private Date datadenacimento;
     private String endereco;
     private String numero;
     private String bairro;
     private String complemento;
     private String cep;
     private String rg;
     private String orgaorg;
     private String cpf;
     private String obs;
     private String escolaridade;
     private String naturalidade;
     private String fonecel;
     private String fonefixo;
     private String email;
     private String nomemae;
     private String nomepai;
     private String sexo;
     private String estadocivil;
     private String tiposangue;
     private String tipopessoa;

     
     private Timestamp datahoracadastro;
     private String cadastradopor;
     
     
     private Integer excluido;
     private String excluidopor;     
     private Timestamp datahoraexclusao;
     
     private Integer alteradopor;     
     private Timestamp datahoraalteracao;

        public Pessoa() {
        }

        public Integer getIdPessoa() {
            return idPessoa;
        }

        public void setIdPessoa(Integer idPessoa) {
            this.idPessoa = idPessoa;
        }

        public Cidade getCidade() {
            return cidade;
        }

        public void setCidade(Cidade cidade) {
            this.cidade = cidade;
        }

        public String getNome() {
            return nome;
        }

        public void setNome(String nome) {
            this.nome = nome;
        }

        public Date getDatadenacimento() {
            return datadenacimento;
        }

        public void setDatadenacimento(Date datadenacimento) {
            this.datadenacimento = datadenacimento;
        }

        public String getEndereco() {
            return endereco;
        }

        public void setEndereco(String endereco) {
            this.endereco = endereco;
        }

        public String getNumero() {
            return numero;
        }

        public void setNumero(String numero) {
            this.numero = numero;
        }

        public String getBairro() {
            return bairro;
        }

        public void setBairro(String bairro) {
            this.bairro = bairro;
        }

        public String getComplemento() {
            return complemento;
        }

        public void setComplemento(String complemento) {
            this.complemento = complemento;
        }

        public String getCep() {
            return cep;
        }

        public void setCep(String cep) {
            this.cep = cep;
        }

        public String getRg() {
            return rg;
        }

        public void setRg(String rg) {
            this.rg = rg;
        }

        public String getOrgaorg() {
            return orgaorg;
        }

        public void setOrgaorg(String orgaorg) {
            this.orgaorg = orgaorg;
        }

        public String getCpf() {
            return cpf;
        }

        public void setCpf(String cpf) {
            this.cpf = cpf;
        }

        public String getObs() {
            return obs;
        }

        public void setObs(String obs) {
            this.obs = obs;
        }

        public String getEscolaridade() {
            return escolaridade;
        }

        public void setEscolaridade(String escolaridade) {
            this.escolaridade = escolaridade;
        }

        public String getNaturalidade() {
            return naturalidade;
        }

        public void setNaturalidade(String naturalidade) {
            this.naturalidade = naturalidade;
        }

        public String getFonecel() {
            return fonecel;
        }

        public void setFonecel(String fonecel) {
            this.fonecel = fonecel;
        }

        public String getFonefixo() {
            return fonefixo;
        }

        public void setFonefixo(String fonefixo) {
            this.fonefixo = fonefixo;
        }

        public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }

        public String getNomemae() {
            return nomemae;
        }

        public void setNomemae(String nomemae) {
            this.nomemae = nomemae;
        }

        public String getNomepai() {
            return nomepai;
        }

        public void setNomepai(String nomepai) {
            this.nomepai = nomepai;
        }

        public String getSexo() {
            return sexo;
        }

        public void setSexo(String sexo) {
            this.sexo = sexo;
        }

        public String getEstadocivil() {
            return estadocivil;
        }

        public void setEstadocivil(String estadocivil) {
            this.estadocivil = estadocivil;
        }

        public String getTiposangue() {
            return tiposangue;
        }

        public void setTiposangue(String tiposangue) {
            this.tiposangue = tiposangue;
        }

        public String getTipopessoa() {
            return tipopessoa;
        }

        public void setTipopessoa(String tipopessoa) {
            this.tipopessoa = tipopessoa;
        }

        public Timestamp getDatahoracadastro() {
            return datahoracadastro;
        }

        public void setDatahoracadastro(Timestamp datahoracadastro) {
            this.datahoracadastro = datahoracadastro;
        }

        public String getCadastradopor() {
            return cadastradopor;
        }

        public void setCadastradopor(String cadastradopor) {
            this.cadastradopor = cadastradopor;
        }

        public Integer getExcluido() {
            return excluido;
        }

        public void setExcluido(Integer excluido) {
            this.excluido = excluido;
        }

        public String getExcluidopor() {
            return excluidopor;
        }

        public void setExcluidopor(String excluidopor) {
            this.excluidopor = excluidopor;
        }

        public Timestamp getDatahoraexclusao() {
            return datahoraexclusao;
        }

        public void setDatahoraexclusao(Timestamp datahoraexclusao) {
            this.datahoraexclusao = datahoraexclusao;
        }

        public Integer getAlteradopor() {
            return alteradopor;
        }

        public void setAlteradopor(Integer alteradopor) {
            this.alteradopor = alteradopor;
        }

        public Timestamp getDatahoraalteracao() {
            return datahoraalteracao;
        }

        public void setDatahoraalteracao(Timestamp datahoraalteracao) {
            this.datahoraalteracao = datahoraalteracao;
        }

        @Override
        public int hashCode() {
            int hash = 7;
            hash = 23 * hash + (this.idPessoa != null ? this.idPessoa.hashCode() : 0);
            return hash;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == null) {
                return false;
            }
            if (getClass() != obj.getClass()) {
                return false;
            }
            final Pessoa other = (Pessoa) obj;
            if (this.idPessoa != other.idPessoa && (this.idPessoa == null || !this.idPessoa.equals(other.idPessoa))) {
                return false;
            }
            return true;
        }

        
        
        

    
    
}

