package br.com.simweb2.model.entities;
// Generated 23/02/2013 11:46:33 by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Unidade generated by hbm2java
 */

@Entity
@Table(name="unidade")

public class Unidade  implements java.io.Serializable {

     private static final long serialVersionUID = -5760179860132496714L;
     
     @Id
     @GeneratedValue
     @Column(name="idUNIDADE", nullable=true)
     private Integer idUnidade;
     
     @ManyToOne(fetch= FetchType.EAGER)
     @JoinColumn(name="CIDADE_idCIDADE")
     private Cidade cidade;
     
     @ManyToOne
     @JoinColumn(name="GESTORUNIDADE_PESSOA_idPESSOA")
     private Gestorunidade gestorunidadePessoaIdPessoa;
     
     private String nomefantasia;
     private String razaosocial;
     private String largadouro;
     private String numero;
     private String complemento;
     private String cnes;
     private String cnpj;
     private String bairro;
     private String cep;
     private String telefone1;
     private String telefone2;
     private String email;
     private String tipodaunidade;
     private String alvara;
     private String alvaraorgexp;
     private String contato;
     
     
     private Timestamp datahoracadastro;     
     private String cadastradopor;   
     
     
     
     private Timestamp datahoradealteracao;
     private String alteradopor;
     
     
     private Timestamp datahoradeexclusao;
     private String excluidopor;
     private Integer excluido;

    public Unidade() {
    }

    public Integer getIdUnidade() {
        return idUnidade;
    }

    public void setIdUnidade(Integer idUnidade) {
        this.idUnidade = idUnidade;
    }

    public Cidade getCidade() {
        return cidade;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    public Gestorunidade getGestorunidadePessoaIdPessoa() {
        return gestorunidadePessoaIdPessoa;
    }

    public void setGestorunidadePessoaIdPessoa(Gestorunidade gestorunidadePessoaIdPessoa) {
        this.gestorunidadePessoaIdPessoa = gestorunidadePessoaIdPessoa;
    }

    public String getNomefantasia() {
        return nomefantasia;
    }

    public void setNomefantasia(String nomefantasia) {
        this.nomefantasia = nomefantasia;
    }

    public String getRazaosocial() {
        return razaosocial;
    }

    public void setRazaosocial(String razaosocial) {
        this.razaosocial = razaosocial;
    }

    public String getLargadouro() {
        return largadouro;
    }

    public void setLargadouro(String largadouro) {
        this.largadouro = largadouro;
    }

    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getComplemento() {
        return complemento;
    }

    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    public String getCnes() {
        return cnes;
    }

    public void setCnes(String cnes) {
        this.cnes = cnes;
    }

    public String getCnpj() {
        return cnpj;
    }

    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    public String getBairro() {
        return bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCep() {
        return cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public String getTelefone1() {
        return telefone1;
    }

    public void setTelefone1(String telefone1) {
        this.telefone1 = telefone1;
    }

    public String getTelefone2() {
        return telefone2;
    }

    public void setTelefone2(String telefone2) {
        this.telefone2 = telefone2;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTipodaunidade() {
        return tipodaunidade;
    }

    public void setTipodaunidade(String tipodaunidade) {
        this.tipodaunidade = tipodaunidade;
    }

    public String getAlvara() {
        return alvara;
    }

    public void setAlvara(String alvara) {
        this.alvara = alvara;
    }

    public String getAlvaraorgexp() {
        return alvaraorgexp;
    }

    public void setAlvaraorgexp(String alvaraorgexp) {
        this.alvaraorgexp = alvaraorgexp;
    }

    public String getContato() {
        return contato;
    }

    public void setContato(String contato) {
        this.contato = contato;
    }

    public Timestamp getDatahoracadastro() {
        return datahoracadastro;
    }

    public void setDatahoracadastro(Timestamp datahoracadastro) {
        this.datahoracadastro = datahoracadastro;
    }

    public String getCadastradopor() {
        return cadastradopor;
    }

    public void setCadastradopor(String cadastradopor) {
        this.cadastradopor = cadastradopor;
    }

    public Timestamp getDatahoradealteracao() {
        return datahoradealteracao;
    }

    public void setDatahoradealteracao(Timestamp datahoradealteracao) {
        this.datahoradealteracao = datahoradealteracao;
    }

    public String getAlteradopor() {
        return alteradopor;
    }

    public void setAlteradopor(String alteradopor) {
        this.alteradopor = alteradopor;
    }

    public Timestamp getDatahoradeexclusao() {
        return datahoradeexclusao;
    }

    public void setDatahoradeexclusao(Timestamp datahoradeexclusao) {
        this.datahoradeexclusao = datahoradeexclusao;
    }

    public String getExcluidopor() {
        return excluidopor;
    }

    public void setExcluidopor(String excluidopor) {
        this.excluidopor = excluidopor;
    }

    public Integer getExcluido() {
        return excluido;
    }

    public void setExcluido(Integer excluido) {
        this.excluido = excluido;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + (this.idUnidade != null ? this.idUnidade.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Unidade other = (Unidade) obj;
        if (this.idUnidade != other.idUnidade && (this.idUnidade == null || !this.idUnidade.equals(other.idUnidade))) {
            return false;
        }
        return true;
    }

    

    
   
}


